# The Dark Navy Band Website Configuration
# This file contains all band-specific content that can be customized

# Site Metadata
site:
  title: "The Dark Navy - Echoes in the Void"
  description: "The Dark Navy: A post-punk, darkwave band with roots in grunge, goth, and hypnagogic pop. Experience the haunting sounds of minimalist expression."
  copyright: "2025 The Dark Navy. All rights reserved."

# Band Information
band:
  name: "The Dark Navy"
  tagline: "Echoes in the Void"
  email: "band@thedarknavy.com"
  
  # Hero Section
  hero:
    background_video: "./assets/videos/hero-background.webm"
    background_fallback: "./assets/images/hero-fallback.webp"
    cta_buttons:
      - text: "Stream on Spotify"
        url: "https://open.spotify.com"
      - text: "Stream on Bandcamp"
        url: "https://bandcamp.com"
    punch:
      enabled: true
      text:
        - "where shadows meet silence..."
        - "echoes of forgotten memories"
        - "drifting through emptiness"
        - "whispers of our souls"
      animation_speed: 1.5

  # About Section
  about:
    heading: "Born from darkness, fueled by emotion"
    image: "./assets/images/band-image.webp"
    bio:
      - "In the shadows between light and sound, we emerged. Not as entertainers, but as vessels for raw emotion. Our sound—a haunting echo in the void of conventional music."
      - "We don't perform; we channel. We don't entertain; we express. Each track is a fragment of consciousness, each note a pulse of existential contemplation."
      - "The past isn't gone. It's reverberating through our instruments, one haunting melody at a time."
    quote:
      text: "The sound of emptiness made tangible"
      audio: "./assets/audio/quote.mp3"

# Music Releases
music:
  section_title: "Latest Releases"
  releases:
    - title: "Spectral Memories"
      type: "audio"
      description: "Our latest single exploring the fragility of memory through minimalist post-punk soundscapes."
      file: "./assets/audio/teaser-1.mp3"
      links:
        - platform: "Spotify"
          url: "https://open.spotify.com"
        - platform: "Bandcamp"
          url: "https://bandcamp.com"
    
    - title: "Void Silhouettes"
      type: "video"
      description: "A visual journey through abandoned spaces and forgotten moments."
      file: "./assets/videos/teaser-1.webm"
      thumbnail: "./assets/images/video-thumbnail.webp"
      links:
        - platform: "YouTube"
          url: "https://youtube.com"
          text: "Watch Full Video"
    
    - title: "Monochrome Whispers"
      type: "audio"
      description: "Exploring the depths of isolation through darkwave and hypnagogic textures."
      file: "./assets/audio/teaser-2.mp3"
      links:
        - platform: "Spotify"
          url: "https://open.spotify.com"
        - platform: "Bandcamp"
          url: "https://bandcamp.com"
    
    - title: "Faded Polaroids"
      type: "audio"
      description: "A melancholic journey through the remnants of forgotten moments."
      file: "./assets/audio/teaser-3.mp3"
      links:
        - platform: "Spotify"
          url: "https://open.spotify.com"
        - platform: "Bandcamp"
          url: "https://bandcamp.com"

# Omni-Channels: The Analog Web of Expression
# All channels included with content fields for posts, links, or media specific to each platform.
# Enabled switch controls visibility in CMS. Content fields allow platform-specific customization (e.g., post text, video links).
channels:
  streaming:
    - platform: "Spotify"
      url: "https://open.spotify.com/artist/thedarknavy"
      icon: "spotify"
      enabled: true
      content:
        post: "Stream our latest track 'Spectral Memories' on Spotify now! #TheDarkNavy #NewRelease"
        link: "https://open.spotify.com/track/spectral-memories"
        media: "./assets/audio/teaser-1.mp3"
    - platform: "Apple Music"
      url: "https://music.apple.com/artist/thedarknavy"
      icon: "apple-music"
      enabled: true
      content:
        post: "Dive into 'Spectral Memories' on Apple Music. Feel the emptiness. #TheDarkNavy"
        link: "https://music.apple.com/track/spectral-memories"
        media: "./assets/audio/teaser-1.mp3"
    - platform: "Bandcamp"
      url: "https://thedarknavy.bandcamp.com"
      icon: "bandcamp"
      enabled: true
      content:
        post: "Experience 'Spectral Memories' on Bandcamp. Support independent music. #TheDarkNavy #PostPunk"
        link: "https://thedarknavy.bandcamp.com/track/spectral-memories"
        media: "./assets/audio/teaser-1.mp3"
    - platform: "SoundCloud"
      url: "https://soundcloud.com/thedarknavy"
      icon: "soundcloud"
      enabled: true
      content:
        post: "Get lost in 'Spectral Memories' on SoundCloud. #TheDarkNavy #Darkwave"
        link: "https://soundcloud.com/thedarknavy/spectral-memories"
        media: "./assets/audio/teaser-1.mp3"

  social:
    - platform: "Instagram"
      url: "https://instagram.com/thedarknavy"
      icon: "instagram"
      enabled: true
      content:
        post: "New track alert! 'Spectral Memories' is live. #TheDarkNavy #PostPunk #Darkwave"
        link: "https://instagram.com/thedarknavy/post/spectral-memories"
        media: "./assets/images/instagram-post.webp"
      sub_features:
        - name: "Instagram Reels"
          url: "https://instagram.com/thedarknavy/reels"
          enabled: true
          content:
            post: "A glimpse into 'Spectral Memories' on Reels! #TheDarkNavy #Reels"
            link: "https://instagram.com/thedarknavy/reels/spectral-memories"
            media: "./assets/videos/reels-teaser.webm"
    - platform: "Facebook"
      url: "https://facebook.com/thedarknavy"
      icon: "facebook"
      enabled: true
      content:
        post: "Our new single 'Spectral Memories' is out! Stream it now. #TheDarkNavy"
        link: "https://facebook.com/thedarknavy/post/spectral-memories"
        media: "./assets/images/facebook-post.webp"
    - platform: "Twitter"
      url: "https://twitter.com/thedarknavy"
      icon: "twitter"
      enabled: true
      content:
        post: "Listen to the void. 'Spectral Memories' out now. #TheDarkNavy #PostPunk #Darkwave"
        link: "https://twitter.com/thedarknavy/status/spectral-memories"
        media: "./assets/images/twitter-post.webp"
    - platform: "YouTube"
      url: "https://youtube.com/@thedarknavy"
      icon: "youtube"
      enabled: true
      content:
        post: "Watch the full 'Void Silhouettes' video on YouTube! #TheDarkNavy #MusicVideo"
        link: "https://youtube.com/watch?v=void-silhouettes"
        media: "./assets/videos/neural-network.webm"
      sub_features:
        - name: "YouTube Shorts"
          url: "https://youtube.com/@thedarknavy/shorts"
          enabled: true
          content:
            post: "'Spectral Memories' in 60 seconds! Check our Shorts. #TheDarkNavy #Shorts"
            link: "https://youtube.com/shorts/spectral-memories"
            media: "./assets/videos/shorts-teaser.webm"

  video:
    - platform: "Vevo"
      url: "https://vevo.com/artist/thedarknavy"
      icon: "vevo"
      enabled: true
      content:
        post: "'Void Silhouettes' music video now live on Vevo! #TheDarkNavy #MusicVideo"
        link: "https://vevo.com/watch/void-silhouettes"
        media: "./assets/videos/neural-network.webm"
    - platform: "YouTube Music"
      url: "https://music.youtube.com/channel/thedarknavy"
      icon: "youtube-music"
      enabled: true
      content:
        post: "Stream 'Spectral Memories' on YouTube Music! #TheDarkNavy #NewRelease"
        link: "https://music.youtube.com/track/spectral-memories"
        media: "./assets/audio/teaser-1.mp3"

  digital_stores:
    - platform: "iTunes"
      url: "https://music.apple.com/artist/thedarknavy"
      icon: "itunes"
      enabled: true
      content:
        post: "Download 'Spectral Memories' on iTunes now! #TheDarkNavy #NewMusic"
        link: "https://music.apple.com/track/spectral-memories"
        media: "./assets/audio/teaser-1.mp3"
    - platform: "Bandcamp"
      url: "https://thedarknavy.bandcamp.com"
      icon: "bandcamp"
      enabled: true
      content:
        post: "Support independent music. Get 'Spectral Memories' on Bandcamp! #TheDarkNavy #PostPunk"
        link: "https://thedarknavy.bandcamp.com/track/spectral-memories"
        media: "./assets/audio/teaser-1.mp3"

  misc:
    - platform: "Local Records USA"
      url: "https://localrecordsusa.com/artists/thedarknavy"
      icon: "record-label"
      enabled: true
      content:
        post: "Proud to be on Local Records USA. Check out our label page! #TheDarkNavy #LocalRecordsUSA"
        link: "https://localrecordsusa.com/artists/thedarknavy"
        media: "./assets/audio/teaser-1.mp3"

# Navigation (updated to include Channels section)
navigation:
  - text: "Home"
    url: "#hero"
  - text: "Music"
    url: "#music"
  - text: "Channels"
    url: "#channels"
  - text: "About"
    url: "#about"
  - text: "Contact"
    url: "#contact"